apps/carts/urls.py
from django.urls import path
# views
from apps.carts.views import AddToCartView, RemoveFromCartView, ShoppinCartListView

app_name = "carts"

urlpatterns = [
    path('shopping-carts/', ShoppinCartListView.as_view(), name="shopping_cart_list"),
    path('add-to-cart/<slug:slug>/', AddToCartView.as_view(), name="add_to_cart"),
    path('remove-cart/<slug:slug>/', RemoveFromCartView.as_view(), name="remove_from_cart")
]

apps/courses/urls.py
from django.urls import path
# views
from apps.courses.views import CourseListview, CourseDetailview

app_name = "courses"

urlpatterns = [
    path('', CourseListview.as_view(), name="course_list"),
    path('<slug:slug>/detail/', CourseDetailview.as_view(), name="course_detail"),
]

apps/generics/urls.py
from django.urls import path
# views
from apps.generics.views import IndexTemplateView, LogoutView, LoginView, SignupView

app_name = "generics"

urlpatterns = [
    path('', IndexTemplateView.as_view(), name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('signup/', SignupView.as_view(), name="signup"),
    path('logout/', LogoutView.as_view(), name="logout")
]

shopping_cart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.generics.urls', namespace="generics")),
    path('cart/', include('apps.carts.urls', namespace="carts")),
    path('courses/', include('apps.courses.urls', namespace="courses"))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve as static_serve
    staticpatterns = static(settings.STATIC_URL, view=static_serve)
    mediapatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = staticpatterns + mediapatterns + urlpatterns

templates/partials/errors.html
{% if form.errors %}
<div class="alert alert-danger alert-dismissible custom-alert" role="alert">
    {% for field in form %}
        {% for error in field.errors %}
            <p>{{ error|escape }}</p>
        {% endfor %}
    {% endfor %}

    {% for error in form.non_field_errors %}
        <p>{{ error|escape }}</p>
    {% endfor %}
</div>
{% endif %}

templates/partials/header.html
{% load static %}
{% load humanize %}
{% load cart_tab %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/">
    <span class="fa fa-home"></span>
    CARRITO DE COMPRAS
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto navbar-right" style="position: absolute; right: 40px;">
      {% if request.user.is_authenticated %}
        <li class="nav-item active dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="fa fa-shopping-cart fa-lg shopping_icon" aria-hidden="true"></span>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <div class="dropdown-menu-custom">
              <strong>Tienes {{ request.user|user_has_total_course }} curso en tu carrito</strong>
              {% with request.user|courses as courses %}
              <ul class="list-group cutosm-list-group">
                  {% for course in courses.courses.all %}
                    {% if course.state %}
                      <li class="list-group-item custom-list-group-item">
                        <a href="#" style="text-decoration:none;">
                          <div class="container-list-group">
                            <img src="{{ course.cover_page.url }}" alt="{{ course.name }}"  width="30" height="30" class="rounded-circle">
                            <span class="list-group-data">
                              <span style="width: 180px;">{{ course.name }}</span>
                              {% if course.is_free %}
                                <span>S/0</span>
                              {% else %}
                                <span>S/{{ course.price }}</span>
                              {% endif %}
                            </span>
                          </div>
                        </a>
                      </li>
                    {% endif %}
                  {% endfor %}
                {% endwith %}
              </ul>
              <div class="dropdown-divider"></div>
              <div style="display: flex; justify-content: space-between; align-items: center;">
                <strong>Total:</strong>
                <strong>S/{{ request.user|total_course|intcomma }}</strong>
              </div>
              <a href="{% url 'carts:shopping_cart_list' %}" class="btn btn-outline-info">
                Ir al carrito
                <span class="fa fa-shopping-cart fa-lg shopping_icon" aria-hidden="true"></span>
              </a>
            </div>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'courses:course_list' %}">
            Cursos
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            Bienvenido {{ request.user.username }}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'generics:logout' %}">
            <span class="fa fa-sign-in" aria-hidden="true"></span>
            Cerrar Sesión
          </a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'generics:signup' %}">
            Registrate
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'generics:login' %}">
            <span class="fa fa-sign-in" aria-hidden="true"></span>
            Iniciar Sesión
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/partials/messages.html
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible custom-alert" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{%endfor%}