apps/carts/urls.py
from django.urls import path
# views
from apps.carts.views import AddToCartView, RemoveFromCartView, ShoppinCartListView

app_name = "carts"

urlpatterns = [
    path('shopping-carts/', ShoppinCartListView.as_view(), name="shopping_cart_list"),
    path('add-to-cart/<slug:slug>/', AddToCartView.as_view(), name="add_to_cart"),
    path('remove-cart/<slug:slug>/', RemoveFromCartView.as_view(), name="remove_from_cart")
]

apps/courses/urls.py
from django.urls import path
# views
from apps.courses.views import CourseListview, CourseDetailview

app_name = "courses"

urlpatterns = [
    path('', CourseListview.as_view(), name="course_list"),
    path('<slug:slug>/detail/', CourseDetailview.as_view(), name="course_detail"),
]

shopping_cart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.generics.urls', namespace="generics")),
    path('cart/', include('apps.carts.urls', namespace="carts")),
    path('courses/', include('apps.courses.urls', namespace="courses"))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve as static_serve
    staticpatterns = static(settings.STATIC_URL, view=static_serve)
    mediapatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = staticpatterns + mediapatterns + urlpatterns

apps/courses/models.py
from django.db import models
from django.template.defaultfilters import slugify
# models accounts
from apps.accounts.models import User

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Cours(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(editable=False, max_length=150, unique=True)
    summary = models.TextField(max_length=250, null=True)
    cover_page = models.ImageField(
        upload_to='baners_cursos', null=True)
    duration = models.IntegerField()
    categorys = models.ManyToManyField(Category)
    state = models.BooleanField(default=True)
    is_free = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    discount = models.DecimalField(
        max_digits=5, decimal_places=2, default=0.00)
    about = models.TextField(max_length=2000, null=True)
    authors = models.ManyToManyField(User)

    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Cours, self).save(*args, **kwargs)

apps/courses/views.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
# model course
from apps.courses.models import Cours
# Create your views here.


class CourseListview(ListView):
    model = Cours
    queryset = Cours.objects.filter(state=True)


class CourseDetailview(DetailView):
    model = Cours
    pk_url_kwarg = 'slug'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, slug=self.kwargs.get('slug'))

templates/courses/cours_detail.html
{% extends 'bases/normal.html' %}
{% load cart_tab %}

{% block content %}
<style>
.parallax {
    /* The image used */
    background-image: url("{{ object.cover_page.url }}");

    /* Set a specific height */
    min-height: 400px;

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    margin-top: -60px;
    opacity: 0.4;
}
.container-fluid{
    width: unset;
    margin-right: unset;
    margin-left: unset;
    padding-right: unset;
    padding-left: unset;
    width: 100%;
}
</style>
<div class="parallax"></div>
<div class="container">
    <div class="row container-row">
        <div class="col-lg-8 col-md-6 col-sm-12">
            <h1>{{ object.name }}</h1>
            <p class="summary-detail ">{{ object.summary }}</p>
            <span>Autores:</span>
            <ul>
                {% for author in object.authors.all %}
                    <li>{{ author.username|upper }}</li>
                {% endfor %}
            </ul>
            <span>Fecha de creación:</span>
            <ul>
                <li>{{ object.created_at }}</li>
            </ul>
            <h4>Sobre el Curso:</h4>
            <p style="text-align:justify; line-height: 1.5;">{{ object.about }}</p>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 card-detail-container">
            <div class="card custom-card" style="box-shadow: 1px 1px 15px 0px rgba(0,0,0,0.30);">
                <img class="card-img-top" src="{{ object.cover_page.url }}" alt="{{ object.name }}" style="max-height: 200px;">
                <div class="card-body">
                    <h3 class="text-info">
                        {{ object.name }}
                    </h3>
                    {% if object.is_free %}
                        <p class="card-text text-wrap" >Precio: Gratis</p>
                    {% else %}
                        <p class="card-text text-wrap" >Precio: S/{{ object.price }}</p>
                    {% endif %}
                    <p class="card-text text-wrap" >
                        Categoria:
                        {% for category in object.categorys.all %}
                            {{ category|title }}
                            {% if not forloop.last %},{% endif %}
                        {% endfor %}
                    </p>
                </div>
                {% if not object|user_has_course:request.user %}
                    <form action="{% url 'carts:add_to_cart' object.slug %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-info" style="margin:15px; width: 90%;">
                            Añadir al carrito
                            <span class="fa fa-shopping-cart fa-lg shopping_icon" aria-hidden="true"></span>
                        </button>
                    </form>
                {% else %}
                    <a href="#" class="btn btn-outline-success" style="margin: 5px 15px;">
                        Añadido al carrito
                        <span class="fa fa-shopping-cart fa-lg shopping_icon" aria-hidden="true"></span>
                    </a>
                    <form action="{% url 'carts:remove_from_cart' object.slug %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger" style="margin: 0 0 15px 15px; width: 90%;">
                            Remover del carrito
                            <span class="fa fa-shopping-cart fa-lg shopping_icon" aria-hidden="true"></span>
                        </button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/courses/cours_list.html
{% extends 'bases/normal.html' %}
{% load cart_tab %}
{% block content %}
<div class="row">
	<div class="col-sm-12">
		<div class="row" style="justify-content: center;">
			{% for course in object_list %}
				<a href="#" style="justify-content: center; display: flex;">
					<div class="card custom-card">
						<img class="card-img-top" src="{{ course.cover_page.url }}" alt="{{ course.name }}" style="max-height: 200px;">
						<div class="card-body">
							<h3 class="text-info">
								<a href="{% url 'courses:course_detail' course.slug %}">
									{{ course.name }}
								</a>
							</h3>
							<p class="card-text text-wrap">{{ course.summary }}</p>
							{% if course.is_free %}
								<p class="card-text text-wrap" >Precio: Gratis</p>
							{% else %}
								<p class="card-text text-wrap" >Precio: S/{{ course.price }}</p>
							{% endif %}
							<p class="card-text text-wrap" >Profesor: {{ course.authors.all.0.username|title }}</p>
						</div>
						{% if not course|user_has_course:request.user %}
							<form action="{% url 'carts:add_to_cart' course.slug %}" method="post">
								{% csrf_token %}
								<button type="submit" class="btn btn-outline-info" style="margin:15px; width: 90%;">
									Añadir al carrito
									<span class="fa fa-shopping-cart fa-lg shopping_icon" aria-hidden="true"></span>
								</button>
							</form>
						{% else %}
							<a href="{% url 'carts:shopping_cart_list' %}" class="btn btn-outline-success" style="margin: 5px 15px;">
								Ver Carrito
								<span class="fa fa-shopping-cart fa-lg shopping_icon" aria-hidden="true"></span>
							</a>
							<form action="{% url 'carts:remove_from_cart' course.slug %}" method="post">
								{% csrf_token %}
								<button type="submit" class="btn btn-outline-danger" style="margin: 0 0 15px 15px; width: 90%;">
									Remover del carrito
									<span class="fa fa-shopping-cart fa-lg shopping_icon" aria-hidden="true"></span>
								</button>
							</form>
						{% endif %}
					</div>
				</a>
			{% empty %}
				<h1>No hay cursos disponibles</h1>
			{% endfor %}
		</div>
	</div>
</div>


{% endblock content %}